#pragma once

/* Base version of the PSVietHoa AutoLoader (WKAL) content.
 * Bump this when the autoloader frontend changes — it triggers the app-cache
 * update and also marks the matching WKALI installer build. */
#define WKAL_VERSION "0.1.0"

/* Full build version (stable: <base>, dev: <base>-dev-<hash|timestamp>),
 * generated by tools/gen_version.py — see include/wkali_version.h */
#include "wkali_version.h"

/* Network Settings — arbitrary port, chosen to avoid colliding with other
 * homebrew HTTP servers (must match the deeplink in assets/param.json.template).
 * 18182 (not upstream's 18181) keeps this fork's AppCache fully separate from
 * the original WebKit Autoloader's. */
#define WKALI_PORT 18182

/* Title ID of the installed homescreen app ("PSVietHoa AutoLoader").
 * Deliberately different from upstream's WKAL00001 so this fork installs as
 * a separate app and never overwrites the original WebKit Autoloader. */
#define WKAL_TITLE_ID "PSVH00001"

/* Process identity — used to kill stale installer instances on startup */
#define WKALI_THREAD_NAME "wkali.elf"

/* Routes */
#define ROUTE_INDEX "/"
#define ROUTE_INDEX_HTML "/index.html"
#define ROUTE_CACHE_MANIFEST "/cache.appcache"
#define ROUTE_INSTALL "/install"
#define ROUTE_VERSION "/version"
#define ROUTE_CLEAR_WEBKIT_DATA "/clear-webkit-data"
#define ROUTE_EXIT "/exit"

/* Logging (implementation in log.c) */
void wkali_log(const char *fmt, ...);
size_t wkali_wait_logs(size_t *pos, char *out_buf, size_t max_len);
void wkali_log_wakeup(void);

/* Notifications (declared in notification.h) */
#include "notification.h"
